[package]
name = "rinecs-derive"
version = "0.1.0"
authors = ["Arturo Castro <arturo@openframeworks.cc>"]
description = "Derive proc macro for rinecs"

[dependencies]
syn = "0.11"
quote = "0.3"

[lib]
proc-macro = true
